# Generated by Django 3.0.8 on 2020-07-08 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRRRPred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_idx', models.CharField(max_length=16)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('fcst_datetime', models.DateTimeField()),
                ('pred_datetime', models.DateTimeField()),
                ('water_temp', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('owner', models.CharField(max_length=256)),
                ('contact_name', models.CharField(max_length=256)),
                ('contact_email', models.CharField(max_length=256)),
                ('lake_name', models.CharField(max_length=256)),
                ('loc_desc', models.CharField(max_length=256)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('elevation', models.DecimalField(decimal_places=1, max_digits=4)),
                ('water_depth', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sensor_type', models.CharField(max_length=256)),
                ('ob_freq', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('water_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ob_depth', models.DecimalField(decimal_places=1, max_digits=4)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Station')),
            ],
        ),
    ]
