# Generated by Django 3.0.8 on 2020-09-03 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRRRPred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_idx', models.CharField(max_length=16)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('fcst_datetime', models.DateTimeField()),
                ('pred_datetime', models.DateTimeField()),
                ('water_temp', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('uident', models.IntegerField()),
                ('geojson', models.CharField(max_length=1024)),
                ('hrrr_gridpoints', models.CharField(max_length=2048)),
                ('sst_gridpoints', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_id', models.CharField(default=None, max_length=16, null=True)),
                ('name', models.CharField(max_length=256)),
                ('owner', models.CharField(default=None, max_length=256, null=True)),
                ('contact_name', models.CharField(default=None, max_length=256, null=True)),
                ('contact_email', models.CharField(default=None, max_length=256, null=True)),
                ('url', models.CharField(default=None, max_length=256, null=True)),
                ('loc_desc', models.CharField(max_length=256)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('elevation', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True)),
                ('water_depth', models.DecimalField(decimal_places=1, default=None, max_digits=4, null=True)),
                ('sensor_type', models.CharField(default=None, max_length=256, null=True)),
                ('ob_freq', models.CharField(default=None, max_length=256, null=True)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Lake')),
            ],
        ),
        migrations.CreateModel(
            name='Ob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(default=None, max_length=256, null=True)),
                ('datetime', models.DateTimeField()),
                ('water_temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ob_depth', models.DecimalField(decimal_places=1, max_digits=4)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Station')),
            ],
        ),
    ]
