# Generated by Django 3.0.8 on 2020-09-04 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSTPred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_idx', models.CharField(max_length=16)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('datetime', models.DateTimeField()),
                ('water_temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Lake')),
            ],
        ),
    ]
