# Generated by Django 3.0.8 on 2020-07-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ob',
            name='sensor_name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='station',
            name='str_id',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ob',
            name='ob_depth',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=4),
        ),
        migrations.AlterField(
            model_name='station',
            name='contact_email',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='station',
            name='contact_name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='station',
            name='elevation',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=4),
        ),
        migrations.AlterField(
            model_name='station',
            name='sensor_type',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='station',
            name='water_depth',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=4),
        ),
    ]
