# Generated by Django 3.0.8 on 2020-11-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sstpred'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='gnis_id',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lake',
            name='uident',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
