# Generated by Django 3.0.8 on 2020-07-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200710_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrrrpred',
            name='water_temp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ob',
            name='water_temp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
