# Generated by Django 3.0.8 on 2020-07-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200710_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ob',
            name='ob_depth',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
